In [1]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine

#importing csv and initial impression of data
df = pd.read_csv("flight_data_2018_2024.csv")
print(df.shape)
print(df.dtypes)
print(df.head())
print(df.isnull().sum())

/var/folders/34/zh4344gx1wvcwgwg161b0jtm0000gn/T/ipykernel_66672/3218455421.py:6: DtypeWarning: Columns (0: Originally_Scheduled_Code_Share_Airline, 1: IATA_Code_Originally_Scheduled_Code_Share_Airline, 2: Div2Airport, 3: Div2TailNum, 4: Div3Airport, 5: Div3TailNum) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("flight_data_2018_2024.csv")

(582425, 120)
Year                  int64
Quarter               int64
Month                 int64
DayofMonth            int64
DayOfWeek             int64
                     ...
Div5LongestGTime    float64
Div5WheelsOff       float64
Div5TailNum         float64
Duplicate               str
Unnamed: 119        float64
Length: 120, dtype: object
   Year  Quarter  Month  DayofMonth  DayOfWeek  FlightDate  \
0  2024        1      1          14          7  2024-01-14
1  2024        1      1          14          7  2024-01-14
2  2024        1      1          14          7  2024-01-14
3  2024        1      1          14          7  2024-01-14
4  2024        1      1          14          7  2024-01-14

  Marketing_Airline_Network Operated_or_Branded_Code_Share_Partners  \
0                        UA                            UA_CODESHARE
1                        UA                            UA_CODESHARE
2                        UA                            UA_CODESHARE
3                        UA                            UA_CODESHARE
4                        UA                            UA_CODESHARE

   DOT_ID_Marketing_Airline IATA_Code_Marketing_Airline  ...  Div5Airport  \
0                     19977                          UA  ...          NaN
1                     19977                          UA  ...          NaN
2                     19977                          UA  ...          NaN
3                     19977                          UA  ...          NaN
4                     19977                          UA  ...          NaN

  Div5AirportID  Div5AirportSeqID Div5WheelsOn  Div5TotalGTime  \
0           NaN               NaN          NaN             NaN
1           NaN               NaN          NaN             NaN
2           NaN               NaN          NaN             NaN
3           NaN               NaN          NaN             NaN
4           NaN               NaN          NaN             NaN

  Div5LongestGTime  Div5WheelsOff Div5TailNum Duplicate  Unnamed: 119
0              NaN            NaN         NaN         N           NaN
1              NaN            NaN         NaN         N           NaN
2              NaN            NaN         NaN         N           NaN
3              NaN            NaN         NaN         N           NaN
4              NaN            NaN         NaN         N           NaN

[5 rows x 120 columns]
Year                     0
Quarter                  0
Month                    0
DayofMonth               0
DayOfWeek                0
                     ...
Div5LongestGTime    582425
Div5WheelsOff       582425
Div5TailNum         582425
Duplicate                0
Unnamed: 119        582425
Length: 120, dtype: int64

In [2]:
#deleting all columns with more than 580000 null values as they represent edge cases that are not relevant for us
null_values = df.isna().sum()
cols_to_del1 = null_values[null_values >= 580000].index
print(cols_to_del1)
df_clean = df.drop(columns=cols_to_del1)
print(df_clean.isnull().sum())

Index(['Originally_Scheduled_Code_Share_Airline',
       'DOT_ID_Originally_Scheduled_Code_Share_Airline',
       'IATA_Code_Originally_Scheduled_Code_Share_Airline',
       'Flight_Num_Originally_Scheduled_Code_Share_Airline', 'DivReachedDest',
       'DivActualElapsedTime', 'DivArrDelay', 'DivDistance', 'Div1Airport',
       'Div1AirportID', 'Div1AirportSeqID', 'Div1WheelsOn', 'Div1TotalGTime',
       'Div1LongestGTime', 'Div1WheelsOff', 'Div1TailNum', 'Div2Airport',
       'Div2AirportID', 'Div2AirportSeqID', 'Div2WheelsOn', 'Div2TotalGTime',
       'Div2LongestGTime', 'Div2WheelsOff', 'Div2TailNum', 'Div3Airport',
       'Div3AirportID', 'Div3AirportSeqID', 'Div3WheelsOn', 'Div3TotalGTime',
       'Div3LongestGTime', 'Div3WheelsOff', 'Div3TailNum', 'Div4Airport',
       'Div4AirportID', 'Div4AirportSeqID', 'Div4WheelsOn', 'Div4TotalGTime',
       'Div4LongestGTime', 'Div4WheelsOff', 'Div4TailNum', 'Div5Airport',
       'Div5AirportID', 'Div5AirportSeqID', 'Div5WheelsOn', 'Div5TotalGTime',
       'Div5LongestGTime', 'Div5WheelsOff', 'Div5TailNum', 'Unnamed: 119'],
      dtype='str')
Year                       0
Quarter                    0
Month                      0
DayofMonth                 0
DayOfWeek                  0
                       ...
FirstDepTime          577300
TotalAddGTime         577300
LongestAddGTime       577300
DivAirportLandings         0
Duplicate                  0
Length: 71, dtype: int64

In [3]:
#after researching the meaning of each columns, the list below represents the names of all columns that are relevant for the project
relevant_columns = ["FlightDate", "Operating_Airline ", "Tail_Number", "Flight_Number_Operating_Airline", "OriginAirportID", "Origin", "OriginCityName", "DestAirportID", "Dest", "DestCityName", "CRSDepTime", "DepTime", "DepDelay", "DepDel15", "DepartureDelayGroups", "TaxiOut", "WheelsOff", "WheelsOn", "TaxiIn", "CRSArrTime", "ArrTime", "ArrDelay", "ArrDel15", "ArrivalDelayGroups", "Cancelled", "CancellationCode", "Diverted", "CRSElapsedTime", "ActualElapsedTime", "AirTime", "Flights", "Distance", "DistanceGroup", "CarrierDelay", "WeatherDelay", "NASDelay", "SecurityDelay", "LateAircraftDelay"]

#creating df with the relevent columns
df_clean = df_clean[relevant_columns]
df_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 582425 entries, 0 to 582424
Data columns (total 38 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   FlightDate                       582425 non-null  str
 1   Operating_Airline                582425 non-null  str
 2   Tail_Number                      576149 non-null  str
 3   Flight_Number_Operating_Airline  582425 non-null  int64
 4   OriginAirportID                  582425 non-null  int64
 5   Origin                           582425 non-null  str
 6   OriginCityName                   582425 non-null  str
 7   DestAirportID                    582425 non-null  int64
 8   Dest                             582425 non-null  str
 9   DestCityName                     582425 non-null  str
 10  CRSDepTime                       582425 non-null  int64
 11  DepTime                          561029 non-null  float64
 12  DepDelay                         560955 non-null  float64
 13  DepDel15                         560955 non-null  float64
 14  DepartureDelayGroups             560955 non-null  float64
 15  TaxiOut                          560515 non-null  float64
 16  WheelsOff                        560515 non-null  float64
 17  WheelsOn                         560093 non-null  float64
 18  TaxiIn                           560093 non-null  float64
 19  CRSArrTime                       582425 non-null  int64
 20  ArrTime                          560094 non-null  float64
 21  ArrDelay                         558715 non-null  float64
 22  ArrDel15                         558715 non-null  float64
 23  ArrivalDelayGroups               558715 non-null  float64
 24  Cancelled                        582425 non-null  float64
 25  CancellationCode                 22073 non-null   str
 26  Diverted                         582425 non-null  float64
 27  CRSElapsedTime                   582425 non-null  float64
 28  ActualElapsedTime                558715 non-null  float64
 29  AirTime                          558715 non-null  float64
 30  Flights                          582425 non-null  float64
 31  Distance                         582425 non-null  float64
 32  DistanceGroup                    582425 non-null  int64
 33  CarrierDelay                     134575 non-null  float64
 34  WeatherDelay                     134575 non-null  float64
 35  NASDelay                         134575 non-null  float64
 36  SecurityDelay                    134575 non-null  float64
 37  LateAircraftDelay                134575 non-null  float64
dtypes: float64(24), int64(6), str(8)
memory usage: 168.9 MB

In [4]:
#removing whitespaces from column names
df_clean.columns = df_clean.columns.str.strip()

In [5]:
#converting date time columns to proper data types
df_clean["FlightDate"] = pd.to_datetime(df["FlightDate"])
df_clean["FlightDate"].head()

0   2024-01-14
1   2024-01-14
2   2024-01-14
3   2024-01-14
4   2024-01-14
Name: FlightDate, dtype: datetime64[us]

In [6]:
#several columns represent only time-of-day, without date. Some are type int64 and some are floats, some have 3 digits and other 4.
#the loop below converts all columns to int64 before converting to string and finally fills out all 3 digits cells into 4 digits for the to_datetime() method to work
from datetime import time

cols_to_time = ["CRSDepTime", "DepTime", "WheelsOff", "WheelsOn", "CRSArrTime", "ArrTime"]
 
for col in cols_to_time:
    df_clean[col] = pd.to_datetime(df_clean[col].astype('Int64').astype(str).str.zfill(4), format='%H%M', errors='coerce').dt.time
     
print(df_clean[cols_to_time].info())
print(df_clean[cols_to_time].head())

<class 'pandas.DataFrame'>
RangeIndex: 582425 entries, 0 to 582424
Data columns (total 6 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   CRSDepTime  582425 non-null  object
 1   DepTime     560988 non-null  object
 2   WheelsOff   560456 non-null  object
 3   WheelsOn    559889 non-null  object
 4   CRSArrTime  582425 non-null  object
 5   ArrTime     559851 non-null  object
dtypes: object(6)
memory usage: 26.7+ MB
None
  CRSDepTime   DepTime WheelsOff  WheelsOn CRSArrTime   ArrTime
0   17:38:00  18:49:00  19:13:00  20:01:00   19:22:00  20:07:00
1   08:15:00  08:14:00  09:12:00  09:53:00   09:34:00  10:00:00
2   15:40:00  16:54:00  17:35:00  18:16:00   16:56:00  18:22:00
3   06:30:00  06:30:00  07:17:00  08:08:00   07:58:00  08:23:00
4   13:00:00  13:33:00  13:45:00  16:08:00   16:03:00  16:21:00

In [7]:
#converting time interval columns to Int64 -- nullable integer type, which supports NaN, to facilitate interface with sql
cols_to_int = ["DepDelay", "TaxiOut", "TaxiIn", "ArrDelay", "CRSElapsedTime", "ActualElapsedTime", "AirTime", "CarrierDelay", "WeatherDelay", "NASDelay", "SecurityDelay", "LateAircraftDelay"]
for col in cols_to_int:
    df_clean[col] = pd.to_numeric(df_clean[col], errors='coerce').astype('Int64')

print(df_clean[cols_to_int].info())
print(df_clean[cols_to_int].head())

<class 'pandas.DataFrame'>
RangeIndex: 582425 entries, 0 to 582424
Data columns (total 12 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   DepDelay           560955 non-null  Int64
 1   TaxiOut            560515 non-null  Int64
 2   TaxiIn             560093 non-null  Int64
 3   ArrDelay           558715 non-null  Int64
 4   CRSElapsedTime     582425 non-null  Int64
 5   ActualElapsedTime  558715 non-null  Int64
 6   AirTime            558715 non-null  Int64
 7   CarrierDelay       134575 non-null  Int64
 8   WeatherDelay       134575 non-null  Int64
 9   NASDelay           134575 non-null  Int64
 10  SecurityDelay      134575 non-null  Int64
 11  LateAircraftDelay  134575 non-null  Int64
dtypes: Int64(12)
memory usage: 60.0 MB
None
   DepDelay  TaxiOut  TaxiIn  ArrDelay  CRSElapsedTime  ActualElapsedTime  \
0        71       24       6        45             104                 78
1        -1       58       7        26              79                106
2        74       41       6        86              76                 88
3         0       47      15        25              88                113
4        33       12      13        18             123                108

   AirTime  CarrierDelay  WeatherDelay  NASDelay  SecurityDelay  \
0       48             0             0         0              0
1       41             0             0        26              0
2       41             0            74        12              0
3       51             0             0        25              0
4       83            18             0         0              0

   LateAircraftDelay
0                 45
1                  0
2                  0
3                  0
4                  0

In [8]:
#Flights column has the identical value throughout and is therefore meaningless and can be deleted
print(df_clean["Flights"].value_counts())
df_clean = df_clean.drop(columns="Flights")
df_clean.columns

Flights
1.0    582425
Name: count, dtype: int64

Index(['FlightDate', 'Operating_Airline', 'Tail_Number',
       'Flight_Number_Operating_Airline', 'OriginAirportID', 'Origin',
       'OriginCityName', 'DestAirportID', 'Dest', 'DestCityName', 'CRSDepTime',
       'DepTime', 'DepDelay', 'DepDel15', 'DepartureDelayGroups', 'TaxiOut',
       'WheelsOff', 'WheelsOn', 'TaxiIn', 'CRSArrTime', 'ArrTime', 'ArrDelay',
       'ArrDel15', 'ArrivalDelayGroups', 'Cancelled', 'CancellationCode',
       'Diverted', 'CRSElapsedTime', 'ActualElapsedTime', 'AirTime',
       'Distance', 'DistanceGroup', 'CarrierDelay', 'WeatherDelay', 'NASDelay',
       'SecurityDelay', 'LateAircraftDelay'],
      dtype='str')

In [9]:
#convert binary columns to correct data type
cols_to_bin = ["ArrDel15", "Cancelled", "Diverted", "DepDel15"]

for col in cols_to_bin:
    df_clean[col] = df_clean[col].astype(bool)
    
df_clean[cols_to_bin].head()

   ArrDel15  Cancelled  Diverted  DepDel15
0      True      False     False      True
1      True      False     False     False
2      True      False     False      True
3      True      False     False     False
4      True      False     False      True

In [10]:
#removing whitespaces from all string columns
print(df_clean.info())
str_cols = ['Operating_Airline', 'Tail_Number', 'Origin', 'OriginCityName', 'Dest', 'DestCityName','CancellationCode']

for col in str_cols:
    df_clean[col] = df_clean[col].str.strip()
    
df_clean[str_cols].head()

<class 'pandas.DataFrame'>
RangeIndex: 582425 entries, 0 to 582424
Data columns (total 37 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   FlightDate                       582425 non-null  datetime64[us]
 1   Operating_Airline                582425 non-null  str
 2   Tail_Number                      576149 non-null  str
 3   Flight_Number_Operating_Airline  582425 non-null  int64
 4   OriginAirportID                  582425 non-null  int64
 5   Origin                           582425 non-null  str
 6   OriginCityName                   582425 non-null  str
 7   DestAirportID                    582425 non-null  int64
 8   Dest                             582425 non-null  str
 9   DestCityName                     582425 non-null  str
 10  CRSDepTime                       582425 non-null  object
 11  DepTime                          560988 non-null  object
 12  DepDelay                         560955 non-null  Int64
 13  DepDel15                         582425 non-null  bool
 14  DepartureDelayGroups             560955 non-null  float64
 15  TaxiOut                          560515 non-null  Int64
 16  WheelsOff                        560456 non-null  object
 17  WheelsOn                         559889 non-null  object
 18  TaxiIn                           560093 non-null  Int64
 19  CRSArrTime                       582425 non-null  object
 20  ArrTime                          559851 non-null  object
 21  ArrDelay                         558715 non-null  Int64
 22  ArrDel15                         582425 non-null  bool
 23  ArrivalDelayGroups               558715 non-null  float64
 24  Cancelled                        582425 non-null  bool
 25  CancellationCode                 22073 non-null   str
 26  Diverted                         582425 non-null  bool
 27  CRSElapsedTime                   582425 non-null  Int64
 28  ActualElapsedTime                558715 non-null  Int64
 29  AirTime                          558715 non-null  Int64
 30  Distance                         582425 non-null  float64
 31  DistanceGroup                    582425 non-null  int64
 32  CarrierDelay                     134575 non-null  Int64
 33  WeatherDelay                     134575 non-null  Int64
 34  NASDelay                         134575 non-null  Int64
 35  SecurityDelay                    134575 non-null  Int64
 36  LateAircraftDelay                134575 non-null  Int64
dtypes: Int64(12), bool(4), datetime64[us](1), float64(3), int64(4), object(6), str(7)
memory usage: 155.5+ MB
None

,Operating_Airline,Tail_Number,Origin,OriginCityName,Dest,DestCityName,CancellationCode
0,G7,N535GJ,MHT,"Manchester, NH",EWR,"Newark, NJ",NaN
1,G7,N535GJ,IAD,"Washington, DC",EWR,"Newark, NJ",NaN
2,G7,N535GJ,EWR,"Newark, NJ",MHT,"Manchester, NH",NaN
3,G7,N547GJ,STL,"St. Louis, MO",ORD,"Chicago, IL",NaN
4,G7,N504GJ,STL,"St. Louis, MO",IAD,"Washington, DC",NaN

In [11]:
#checking for duplicate rows
print(df_clean.duplicated().sum())

0

In [12]:
#column names to lowercase to facilitate importing into sql db
df_clean.columns = df_clean.columns.str.lower()

df_clean.columns

Index(['flightdate', 'operating_airline', 'tail_number',
       'flight_number_operating_airline', 'originairportid', 'origin',
       'origincityname', 'destairportid', 'dest', 'destcityname', 'crsdeptime',
       'deptime', 'depdelay', 'depdel15', 'departuredelaygroups', 'taxiout',
       'wheelsoff', 'wheelson', 'taxiin', 'crsarrtime', 'arrtime', 'arrdelay',
       'arrdel15', 'arrivaldelaygroups', 'cancelled', 'cancellationcode',
       'diverted', 'crselapsedtime', 'actualelapsedtime', 'airtime',
       'distance', 'distancegroup', 'carrierdelay', 'weatherdelay', 'nasdelay',
       'securitydelay', 'lateaircraftdelay'],
      dtype='str')

In [13]:
#establishing connection to postgres database

engine = create_engine("postgresql+psycopg2://airlines:liora@localhost:5432/airlines_db")

In [14]:
df_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 582425 entries, 0 to 582424
Data columns (total 37 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   flightdate                       582425 non-null  datetime64[us]
 1   operating_airline                582425 non-null  str
 2   tail_number                      576149 non-null  str
 3   flight_number_operating_airline  582425 non-null  int64
 4   originairportid                  582425 non-null  int64
 5   origin                           582425 non-null  str
 6   origincityname                   582425 non-null  str
 7   destairportid                    582425 non-null  int64
 8   dest                             582425 non-null  str
 9   destcityname                     582425 non-null  str
 10  crsdeptime                       582425 non-null  object
 11  deptime                          560988 non-null  object
 12  depdelay                         560955 non-null  Int64
 13  depdel15                         582425 non-null  bool
 14  departuredelaygroups             560955 non-null  float64
 15  taxiout                          560515 non-null  Int64
 16  wheelsoff                        560456 non-null  object
 17  wheelson                         559889 non-null  object
 18  taxiin                           560093 non-null  Int64
 19  crsarrtime                       582425 non-null  object
 20  arrtime                          559851 non-null  object
 21  arrdelay                         558715 non-null  Int64
 22  arrdel15                         582425 non-null  bool
 23  arrivaldelaygroups               558715 non-null  float64
 24  cancelled                        582425 non-null  bool
 25  cancellationcode                 22073 non-null   str
 26  diverted                         582425 non-null  bool
 27  crselapsedtime                   582425 non-null  Int64
 28  actualelapsedtime                558715 non-null  Int64
 29  airtime                          558715 non-null  Int64
 30  distance                         582425 non-null  float64
 31  distancegroup                    582425 non-null  int64
 32  carrierdelay                     134575 non-null  Int64
 33  weatherdelay                     134575 non-null  Int64
 34  nasdelay                         134575 non-null  Int64
 35  securitydelay                    134575 non-null  Int64
 36  lateaircraftdelay                134575 non-null  Int64
dtypes: Int64(12), bool(4), datetime64[us](1), float64(3), int64(4), object(6), str(7)
memory usage: 155.5+ MB

In [15]:
#populating weather table in postgres db
df_clean.to_sql("flights", engine, if_exists="append", index=False, schema="bronze")

528

In [16]:
#testing if importing worked
df_check = pd.read_sql("SELECT * FROM bronze.flights LIMIT 5", engine)
print(df_check)
print(df_check.info())

   flight_id  flightdate operating_airline tail_number  \
0          1  2024-01-14                G7      N535GJ
1          2  2024-01-14                G7      N535GJ
2          3  2024-01-14                G7      N535GJ
3          4  2024-01-14                G7      N547GJ
4          5  2024-01-14                G7      N504GJ

   flight_number_operating_airline  originairportid origin  origincityname  \
0                             4432            13296    MHT  Manchester, NH
1                             4430            12264    IAD  Washington, DC
2                             4429            11618    EWR      Newark, NJ
3                             4428            15016    STL   St. Louis, MO
4                             4427            15016    STL   St. Louis, MO

   destairportid dest  ... actualelapsedtime airtime distance  distancegroup  \
0          11618  EWR  ...                78      48    209.0              1
1          11618  EWR  ...               106      41    212.0              1
2          13296  MHT  ...                88      41    209.0              1
3          13930  ORD  ...               113      51    258.0              2
4          12264  IAD  ...               108      83    696.0              3

   carrierdelay  weatherdelay  nasdelay securitydelay lateaircraftdelay  \
0             0             0         0             0                45
1             0             0        26             0                 0
2             0            74        12             0                 0
3             0             0        25             0                 0
4            18             0         0             0                 0

                 ingested_at
0 2026-04-23 10:10:39.733939
1 2026-04-23 10:10:39.733939
2 2026-04-23 10:10:39.733939
3 2026-04-23 10:10:39.733939
4 2026-04-23 10:10:39.733939

[5 rows x 40 columns]
<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 40 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   flight_id                        5 non-null      int64
 1   flightdate                       5 non-null      object
 2   operating_airline                5 non-null      str
 3   tail_number                      5 non-null      str
 4   flight_number_operating_airline  5 non-null      int64
 5   originairportid                  5 non-null      int64
 6   origin                           5 non-null      str
 7   origincityname                   5 non-null      str
 8   destairportid                    5 non-null      int64
 9   dest                             5 non-null      str
 10  destcityname                     5 non-null      str
 11  crsdeptime                       5 non-null      object
 12  deptime                          5 non-null      object
 13  depdelay                         5 non-null      int64
 14  depdel15                         5 non-null      bool
 15  departuredelaygroups             5 non-null      float64
 16  taxiout                          5 non-null      int64
 17  wheelsoff                        5 non-null      object
 18  wheelson                         5 non-null      object
 19  taxiin                           5 non-null      int64
 20  crsarrtime                       5 non-null      object
 21  arrtime                          5 non-null      object
 22  arrdelay                         5 non-null      int64
 23  arrdelayminutes                  0 non-null      object
 24  arrdel15                         5 non-null      bool
 25  arrivaldelaygroups               5 non-null      float64
 26  cancelled                        5 non-null      bool
 27  cancellationcode                 0 non-null      object
 28  diverted                         5 non-null      bool
 29  crselapsedtime                   5 non-null      int64
 30  actualelapsedtime                5 non-null      int64
 31  airtime                          5 non-null      int64
 32  distance                         5 non-null      float64
 33  distancegroup                    5 non-null      int64
 34  carrierdelay                     5 non-null      int64
 35  weatherdelay                     5 non-null      int64
 36  nasdelay                         5 non-null      int64
 37  securitydelay                    5 non-null      int64
 38  lateaircraftdelay                5 non-null      int64
 39  ingested_at                      5 non-null      datetime64[us]
dtypes: bool(4), datetime64[us](1), float64(3), int64(17), object(9), str(6)
memory usage: 1.6+ KB
None